<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-AF71NMN" name="Firefox1" tests="5" failures="1" timestamp="27 Nov 2019 16:17:41 GMT" time="0.215" errors="0">
  <testcase name="meth2" time="0.0" classname="com.rippon.Class1Test"/>
  <testcase name="meth3" time="0.0" classname="com.rippon.Class1Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.rippon.Class1Test.meth3(Class1Test.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- meth3 -->
  <testcase name="meth4" time="0.0" classname="com.rippon.Class1Test"/>
  <testcase name="skipTest" time="0.001" classname="com.rippon.Class1Test">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase name="meth1" time="0.0" classname="com.rippon.Class2Test"/>
</testsuite> <!-- Firefox1 -->
